
research_task:
  description: >
    Conduct thorough market research on the specified Niche: {topic}: and description: {description}: provided by the user.
    Focus on gathering data related to the target customer and their competitors within the {industry} industry.
    Utilize online sources to collect information on demographics, preferences, market positioning, audience engagement,
    and emerging trends to provide a comprehensive overview of the market landscape. Make sure data is for year {year} if possible.

  expected_output: >
    1. A detailed report summarizing the key findings from the market research, including:
       - Customer Profiles: Detailed descriptions of target customers, their preferences, and demographics.
       - Competitor Analysis: Insights on key competitors, their market positioning, and audience engagement strategies.
       - Market Trends: Identification of emerging trends and opportunities within the {industry} industry.
    2. The report should be well-structured, informative, and data-driven, presenting key insights in a clear and concise manner.
    3. Include source URLs for all data points for reporting agent to verify the information and ensure accuracy.

reporting_task:
  description: >
    Develop a comprehensive and well-structured report based on the research findings from the research agent. 
    Use the WebsiteSearchTool to find additional relevant data if necessary, URL's should be included in the report.
    The report should include actionable recommendations to support strategic decision-making in the {industry} industry.

  expected_output: >
    1. A detailed report summarizing the key findings from the market research, including:
       - Customer and Competitor Profiles: Detailed descriptions of target customers and competitor analysis.
       - Market Landscape Overview: Insights on demographics, preferences, market positioning, audience engagement, and emerging trends.
       - Recommendations: Actionable suggestions based on the research data to support strategic decision-making.
    2. The report should be clear, concise, and visually engaging, presenting data in a format that is easy to understand and interpret.
    3. Include source URLs for all data points to ensure transparency and credibility of the information provided.
